version: "3"

services:
  auth-service:
    container_name: auth-service
    image: auth-service:latest
    ports:
      - "8082:8082"
    environment:
    - DB_HOST=mysql-docker
    - DB_PORT=3306
    - DB_USER=root
    - DB_PASS=ham147532@
    - DB_NAME=J2HB
    - DEBUG=false
    - UPLOAD_PATH=/home/darkseid/Pictures/Test/
    - SERVER_PORT=8082
    - EUREKA_HOST=discovery-service
    - EUREKA_PORT=8761
    networks:
      - j2hb-net
    depends_on:
      - gateway-service

  exam-service:
    container_name: exam-service
    image: exam-service:latest
    ports:
      - "8081:8081"
    environment:
    - DB_HOST=mysql-docker
    - DB_PORT=3306
    - DB_USER=root
    - DB_PASS=ham147532@
    - DB_NAME=J2HB
    - DEBUG=false
    - SERVER_PORT=8081
    - AUTH_HOST=auth-service
    - AUTH_PORT=8082
    - EUREKA_HOST=discovery-service
    - EUREKA_PORT=8761
    networks:
      - j2hb-net
    depends_on:
      - gateway-service

  config-service:
    container_name: config-service
    image: config-service:latest
    ports:
      - "8083:8083"
    environment:
    - DB_HOST=mysql-docker
    - DB_PORT=3306
    - DB_NAME=J2HB
    - DB_USER=root
    - DB_PASS=ham147532@
    - DEBUG=true
    - SERVER_PORT=8083
    - AUTH_HOST=auth-service
    - AUTH_PORT=8082
    - EUREKA_HOST=discovery-service
    - EUREKA_PORT=8761
    networks:
      - j2hb-net
    depends_on:
      - auth-service
  
  gateway-service:
    container_name: gateway-service
    image: gateway-service:latest
    ports:
      - "8080:8080"
    environment:
    - DB_HOST=mysql-docker
    - DB_PORT=3306
    - DB_USER=root
    - DB_PASS=ham147532@
    - DB_NAME=J2HB
    - DEBUG=false
    - AUTH_HOST=auth-service
    - AUTH_PORT=8082
    - EXAM_HOST=exam-service
    - EXAM_PORT=8081
    - CONFIG_HOST=config-service
    - CONFIG_PORT=8083
    - EUREKA_PORT=8761
    - EUREKA_HOST=discovery-service
    - GATEWAY_PORT=8080
    networks:
      - j2hb-net
    depends_on:
      - discovery-service
  
  discovery-service:
    container_name: discovery-service
    image: discovery-service:latest
    ports:
      - "8761:8761"
    environment:
      - DEBUG=false
    networks:
      - j2hb-net
    depends_on:
      - mysql-docker

  mysql-docker:
    container_name: mysql-docker
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=ham147532@
      - MYSQL_DATABASE=J2HB
      - MYSQL_USER=darkseid
      - MYSQL_PASSWORD=ham147532@
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - j2hb-net

networks:
  j2hb-net:
      driver: bridge